on:
  workflow_dispatch:
  push:
  pull_request:

name: ci

jobs:
  test_eas:
    name: Test EAS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: create input
        run: echo 'push1 ff' > input
      - name: run eas
        run: cargo run --features cli --bin eas input ax/x/output || true
      - name: check dir
        run: ls

  test_parent_dir:
    name: Test Parent Directories
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: create input
        run: echo 'push1 0xff' > input
      - name: run eas
        run: cargo run --features cli --bin eas input bx/x/output
      - name: check output
        run: cat px/tx/output
      - name: check parent dir
        run: ls px/tx
      - name: check grandparent dir
        run: ls px
